# Worflow Do Projeto
name: CICD
on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:
    inputs:
      environment:
        description: Ambiente CICD
        type: choice
        required: true
        default: dev
        options: [ main, dev ]
jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositório
        uses: actions/checkout@v3

      - name: Mostra Estrutura Máquina Virtuqal
        run: |
          echo "Estrutura Repositório: "
          ls -la
      
      - name: Mostra Estrutura Diretório
        run: |
          echo "Estrutura Repositório: "
          ls -la api || echo "O Repositório "api" Não Existe..."